### ISSUE TITLE
systemctl commands in my shell

### ISSUE THREAD

**Issue by svrvt** [colonelpanic8/rofi-systemd#10]
Hi. You have a great script and maybe soon I'll be comfortable dealing with services :)
I noticed that I didn't have the service restarted. When installing the script, I was satisfied with just the list full list of services without checking $action.
At first only list_actions was working properly. After I changed the shebang to env bash, "tail" and "boot_log" worked, but the services still wouldn't restart.
I tried to understand the content
```bash
to_run="$(get_command_with_args)"
	if [ ! -t 1 ] && [[ "$to_run" = *"journalctl"* ]]; then
		to_run="$term $to_run"
	else
		to_run="$to_run | less"
	fi
	echo "Running $to_run"
	eval "$to_run"

get_command_with_args() {
	case "$action" in
		"tail")
			echo "journalctl $user_arg -u '$service_name' -f"
			;;
		"boot_logs")
			echo "journalctl $user_arg -u '$service_name' --boot"
			;;
		"list_actions")
			action=$(echo "$all_actions" | $rofi_command "Select action: ")
			get_command_with_args
			;;
		*)
			echo "$command $action '$service_name'"
			;;
	esac
}
```
It comes out that for all $action except "tail" and "boot_log" to_run="$to_run | less"?
Maybe that's why I can only run start stop restart and disable if I change the logic to [ ! -t 1 ] || [[ "$to_run" = *"journalctl "* ]]. Only then I get a terminal window asking for a password. But I'm not sure I understand the [ ! -t ] logic correctly.

**Comment by colonelpanic8** [comment]
you need to have passwordless sudo access for this to work

**Comment by svrvt** [comment]
Great. I've now disabled user password entry for systemct and everything works.
Thank you.
