### ISSUE TITLE
Problems as of systemd 245

### ISSUE THREAD

**Issue by Brottweiler** [colonelpanic8/rofi-systemd#8]
I have been using an old version of this because I got it from your dotfiles. Since systemd 245, i cannot stop or restart services using this script. 

This is the error in the console
```
Running systemctl stop 'redshift.service'
Failed to stop redshift.service: Interactive authentication required.
See system logs and 'systemctl status redshift.service' for details.
```
Redshift is a user service, so it seems like it fails because it can't auth me. But it should try and stop redshift using the `--user` flag, which it doesn't seem to do.

**Comment by colonelpanic8** [comment]
how do you have sudo setup? does sudo require a password for you?

**Comment by Brottweiler** [comment]
Yes, but the redshift service is a user service which does not require authentication. It is managed by the `--user` option, like so `systemctl --user start redshift.service`.

**Comment by colonelpanic8** [comment]
@Brottweiler Yeah I'm running in to this now too. The issue is that the output from systemd has changed, and the previous method of determining whether or not the unit was a system or user unit is no longer working. I'm going to look in to this a bit more and hopefully fix the issue.

**Comment by colonelpanic8** [comment]
@Brottweiler Fixed the issue. Ended up switch to the dbus api for systemd which should allow for backwards compatibility but also fix the issue and any similar future issues moving forward.

**Comment by Brottweiler** [comment]
Thank you for looking into it and fixing it! I appreciate it!
