### ISSUE TITLE
Function definition style

### ISSUE THREAD

**Issue by svrvt** [colonelpanic8/rofi-systemd#9]
Hi,@colonelpanic8 
Thanks for the script. I'm writing to report that I had to change the definitions of all the functions because the script wouldn't run. My lsp gave me a hint and I did the following:
`truncate() {
	awk '{print substr($0, length($0)-'$truncate_length')}'
}...`
After that the script worked.
I have Ubuntu

**Comment by colonelpanic8** [comment]
@RU927 do you know what shell you were using?

**Comment by svrvt** [comment]
> @RU927 знаете ли вы, какую оболочку вы использовали?

$ echo $SHELL 
/usr/bin/zsh
$ echo $ZSH_VERSION
5.8.1

$ which sh
/usr/bin/sh
$ readlink -f /usr/bin/sh
/usr/bin/dash

**Comment by svrvt** [comment]
> @RU927 знаете ли вы, какую оболочку вы использовали?

I've been using Linux for about a year and don't understand much about programming. Until then I thought that only shebang defines the execution programme and the shell only outputs the result.

**Comment by colonelpanic8** [comment]
> $ which sh
> /usr/bin/sh
> $ readlink -f /usr/bin/sh
> /usr/bin/dash

right so this is the reason you had an issue. 

dash is not bash compatible.

both zsh and bash should work with the definitions i had before.

**Comment by svrvt** [comment]
Well, thank you.
Some aspects of this problem have been discussed [here](https://unix.stackexchange.com/questions/217041/finding-out-what-sh-is)
